### ISSUE TITLE
Query / key mixing correct?

### ISSUE THREAD

**Issue by ozppupbg** [fkodom/grouped-query-attention-pytorch#5]
Hello,

I looked at your code, while trying to unterstand the details of GQA. I noticed this part:
https://github.com/fkodom/grouped-query-attention-pytorch/blob/0b5ab637ba225047ea3d65923c40dee23878065b/grouped_query_attention_pytorch/attention.py#L87-L93
If I compare this to the official LLAMA2 implementation
https://github.com/meta-llama/llama/blob/54c22c0d63a3f3c9e77f43a6a3041c00018f4964/llama/model.py#L291-L293
it seems, that the LLAMA2 implementation expands the keys and values to the number of queries and your code reduces the queries to the number of keys and values.

Is this analysis intentional and is this intentional?

**Comment by GengZhengLin** [comment]
Yeah I am sure this implementation is incorrect.

**Comment by fkodom** [comment]
@ozppupbg Thanks for pointing this out, and sorry I missed your original question for so long!

There was a bug in my `scaled_dot_product_gqa` code, which sadly wasn't caught by the unit tests.  I just pushed a fix, and updated the unit tests to check that `scaled_dot_product_gqa` is equivalent to `F.scaled_dot_product_attention` if we duplicate the KV heads as in Llama2.

It shouldn't be necessary to duplicate the KV heads, but in practice it's significantly faster than my implementation, because it allows you to use `F.scaled_dot_product_attention`, which in turn uses Flash Attention 2.

Here's a rough script to confirm what I was going for (now consistent with the repo):
```python
import torch
import torch.nn.functional as F
from einops import einsum, rearrange

batch_size = 2
num_heads = 8
num_head_groups = 4
seq_len = 128
dim = 64

scale = dim**-0.5
query = torch.randn(batch_size, num_heads, seq_len, dim)
key = torch.randn(batch_size, num_heads // num_head_groups, seq_len, dim)
value = torch.randn(batch_size, num_heads // num_head_groups, seq_len, dim)

# --- Group by folding (gqa-pytorch) ---
# Separate the query heads into 'num_head_groups' chunks, and fold the group
# dimension into the batch dimension.  This allows us to compute the attention
# for each head in parallel, then sum over all of the groups at the end.
query_ = rearrange(query, "b (h g) n d -> b g h n d", g=num_head_groups)
similarity = einsum(query_, key, "b g h n d, b h s d -> b g h n s")
attention = F.softmax(similarity / scale, dim=-1)
out1 = einsum(attention, value, "b g h n s, b h s d -> b g h n d")
# Unfold the groups back into the head dimension
out1 = rearrange(out1, "b g h n d -> b (h g) n d")

# --- Duplicate heads (Llama2) ---
# Duplicate the key/value heads, so the following operations are equivalent to MHA
key_ = key.repeat_interleave(num_head_groups, dim=1)
value_ = value.repeat_interleave(num_head_groups, dim=1)
similarity = einsum(query, key_, "b h n d, b h s d -> b h n s")
attention = F.softmax(similarity / scale, dim=-1)
out2 = einsum(attention, value_, "b h n s, b h s d -> b h n d")

torch.testing.assert_close(out1, out2)
```

Sorry again for the delay, and I hope this helps!
